jobs:
  - job: build_test_deploy
    steps:
    - task: Bash@3
      displayName: Bash Commands
      inputs:
       targetType: 'inline'
       script: |
        # Write your commands here
        mkdir ~/.ssh
        echo $(PrivateKey) > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo $(PublicKey) > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        mkdir ~/portal
        cd ~/portal
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"  GIT_TRACE=1 GIT_CURL_VERBOSE=1 $(GitCloneUrl)
        ls -ltrR ./
    - task: Maven@3
      displayName: Maven Compile
      inputs:
       mavenPomFile: 'pom.xml'
       options: -B compile -DskipTests=true
       mavenOptions: '-Xmx3072m'
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.11'
       jdkArchitectureOption: 'x64'
       publishJUnitResults: false

    - task: SonarCloudPrepare@1
      displayName: Prepare Sonar Cloud
      inputs:
       SonarCloud: 'Sonar Cloud'
       organization: 'nkbali'
       scannerMode: 'Other'
       
    - task: Maven@3
      displayName: Sonar Analysis
      inputs:
       mavenPomFile: 'pom.xml'
       options: -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
       mavenOptions: '-Xmx3072m'
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.11'
       jdkArchitectureOption: 'x64'
       publishJUnitResults: true
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       sqAnalysisEnabled: true

    - task: SonarCloudPublish@1
      displayName: Sonar Publish
      inputs:
       pollingTimeoutSec: '300'

    - task: PowerShell@2
      displayName: Check Quality Gate
      inputs:
       targetType: 'inline'
       script: |
         $token="$(SonarToken)"
         $tokenBytes = [Text.Encoding]::Unicode.GetBytes($token)
         $base64 = [System.Convert]::ToBase64String($tokenBytes)
         $basicAuth = [string]::Format("Basic {0}", $base64)
         $result = Invoke-RestMethod -Method Get -Uri https://sonarcloud.io/api/qualitygates/project_status?projectKey=$(SonarProjectKey)
         $result | ConvertTo-Json | Write-Host
         if ($result.projectStatus.status -eq "OK") {
         Write-Host "Quality Gate Succeeded"
         } else {
         throw "Quality gate failed"
         }
            
    - task: CopyFiles@2
      displayName: Copy Jar File
      condition: and(succeeded(), not(contains(variables['Build.SourceBranch'], 'refs/heads/feature')))
      inputs:
       SourceFolder: '$(build.sourcesdirectory)'
       Contents: 'target/*.jar'
       TargetFolder: '$(build.artifactstagingdirectory)'

    - task: CopyFiles@2
      displayName: Copy Docker File
      condition: and(succeeded(), not(contains(variables['Build.SourceBranch'], 'refs/heads/feature')))
      inputs:
       SourceFolder: '$(build.sourcesdirectory)'
       Contents: 'Dockerfile'
       TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: and(succeeded(), not(contains(variables['Build.SourceBranch'], 'refs/heads/feature')))
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'Container'

    - task: Docker@2
      displayName: Docker Build and Push
      condition: and(succeeded(), not(contains(variables['Build.SourceBranch'], 'refs/heads/feature')))
      inputs:
       containerRegistry: 'Azure Openshift Docker Registry'
       repository: $(RespositoryName)
       command: 'buildAndPush'
       Dockerfile: 'Dockerfile'
       tags: |
         $(Build.BuildNumber)
         latest
